### ISSUE TITLE
Add launcher icon

### ISSUE THREAD

**Issue by manojsinghnegiwd** [recraftrelic/react-native-chat-app-boilerplate#27]

**Comment by manojsinghnegiwd** [comment]
@yashkapoor8710 https://medium.com/better-programming/react-native-add-app-icons-and-launch-screens-onto-ios-and-android-apps-3bfbc20b7d4c

**Comment by yashkapoor8710** [comment]
I have fixed this issue
https://github.com/recraftrelic/react-native-chat-app-boilerplate/pull/32
