### ISSUE TITLE
'RNSplashScreen.h' file not found

### ISSUE THREAD

**Issue by manojsinghnegiwd** [recraftrelic/react-native-chat-app-boilerplate#47]
![Screenshot 2020-03-22 at 1 37 02 PM](https://user-images.githubusercontent.com/7533769/77245144-68327500-6c42-11ea-937b-bc7fb7c5821c.png)

I am geting this error after the newest splashscreen changes

**Comment by yashkapoor8710** [comment]
Try to reclone the repo
